# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: troand
# "service" is the name of this project. This will also be added to your AWS resource names.
service: bonzai

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-north-1
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: '*'
 
build:
  esbuild:
    minify: true

functions:
  hello:
    handler: index.handler
    events:
      - httpApi:
          path: /
          method: get
