# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: molnmiljo
# "service" is the name of this project. This will also be added to your AWS resource names.
service: bonzai

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-north-1
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: "*"

build:
  esbuild:
    minify: true

functions:
  getBooking:
    handler: functions/getBooking/index.handler
    events:
      - httpApi:
          path: /bookings
          method: GET

  postBooking:
    handler: functions/postBooking/index.handler
    events:
      - httpApi:
          path: /bookings
          method: POST

  putId:
    handler: functions/putId/index.handler
    events:
      - httpApi:
          path: /bookings/{id}
          method: PUT

  deleteId:
    handler: functions/deleteId/index.handler
    events:
      - httpApi:
          path: /bookings/{id}
          method: DELETE

resources:
  Resources:
    bonzaiInventory:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: bonzaiInventory
        AttributeDefinitions:
          - AttributeName: roomId
            AttributeType: S
        KeySchema:
          - AttributeName: roomId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
    bonzaiBookings:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: bonzaiBookings
        AttributeDefinitions:
          - AttributeName: bookingId
            AttributeType: S
        KeySchema:
          - AttributeName: bookingId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
